import os
from dotenv import load_dotenv
from cassandra.cluster import Cluster
from cassandra.query import SimpleStatement
from cassandra.auth import PlainTextAuthProvider
load_dotenv()
# This secure connect bundle is autogenerated when you download your SCB, 
# if yours is different update the file name below
'''
cloud_config= {
  'secure_connect_bundle': 'core/gorgumu/secure-connect-cbdc.zip'
}
CLIENT_ID = os.getenv('CASSANDRA_ID')
CLIENT_SECRET = os.getenv('CASSANDRA_SECRET')
auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect()
'''

usr = os.getenv("USERAME")
passwd = os.getenv("PASSWORD")
cluster = Cluster()  # Replace with your Cassandra node IP
session = cluster.connect('gorgumu')